name: lhat
channels:
  - conda-forge
dependencies:
  - rasterstats
  - geopandas
  - numpy
  - scipy
  - rasterio
  - rioxarray
  - owslib
  - earthengine-api
  - pytest
  - pandas
  - scikit-learn
  - gdal
